### PR TITLE
SABRE looping behavior

### PR DESCRIPTION
**Pull request by csookim**
There is a looping behavior in Qibo SABRE. 
To address this in Qibo, can I create an issue with this notebook?

### CODE REVIEW

**Review by marekgluza — COMMENTED** [review]
Yes, opening a qibo issue with the bug label is probably the way to go. Before you post it to more people, can you post here the description?

We could view this as a scientific writing exercise. I will evaluate if the text will likely allow the qibo core devs to understand what happens in the bug

The notebook seems nice, thanks. You should stress that it has a proposed fix of the bug. The goal of the issue is to get green lights to open a PR and implement a fix - or something more is needed?

**Comment by csookim** [comment]
# Looping Behavior in Qibo SABRE

## Introduction

When the SABRE router encounters a two-qubit gate that cannot be executed due to hardware constraints, it adds a sequence of SWAPs to make the two-qubit gate executable. SABRE generates candidate SWAPs and selects one based on a defined formula. This process is repeated until the two-qubit gate becomes executable. However, since SABRE is a heuristic algorithm, the process can sometimes get stuck in a loop.

## Problem

In some cases, SABRE adds a repeated sequence of similar SWAPs. For example, a 10-qubit circuit with the following connectivity:

```python
qubit_array = [(7, 2), (6, 0), (5, 6), (4, 8), (3, 5), (9, 1)]
```

is routed with 156 SWAPs using the Trivial placer and SABRE router. This example is illustrated in the [notebook](https://github.com/csookim/qibo_transpiler_cskim/blob/bff207ebc519313701bf0f724a757aeee243a6e6/cskim/docs/transpiler_general/21-1_qibo_sabre_looping.ipynb).


## Solution

To solve this, the number of SWAPs is managed until every routing is made.

```python
...        
    self.circuit.update(best_candidate)   # SWAP is added
    self._added_swaps += 1
...
```

`_added_swaps` is counted after one SWAP is picked from the candidate SWAPs. If routing is completed (a two-qubit gate becomes executable), `_added_swaps` is reset to 0.

```python
...
    if self._added_swaps > 1.5 * longest_path:  # threshold is arbitrary
        self.circuit = deepcopy(self._saved_circuit)
        self._route_to_nearest_gate()
...
```

If `_added_swaps` exceeds the threshold, the nearest two-qubit gate is routed manually. The two-qubit gate with the minimum distance between the qubits is selected, and qubit 1 is moved adjacent to qubit 2.

Qiskit also has the same issue and the similar solution. [Reference, line 559](https://github.com/Qiskit/qiskit/blob/e5ee1a8d97753ccca09b0c15be7b7ab0c1c84b90/crates/accelerate/src/sabre/route.rs#L559).

## Tests

When routing 30 random CZ circuits with the Random placer and original SABRE router, there are cases where more than 100 SWAPs are added.

drawing

After modification, no such cases were found.

drawing

## Discussion

- Setting the Threshold: The current threshold is set to `1.5 * longest path` in the current connectivity. This value is somewhat arbitrary and might need tuning. 

- Routing the Nearest Two-Qubit Gate: Currently, the algorithm routes the nearest two-qubit gate by moving qubit 1 adjacent to qubit 2. This method ensures the selected gate will be routed, but alternative strategies might be considered.

**Comment by marekgluza** [comment]
Excellent, thank you!

the formulation of what exactly is the issue could be extended to say what/how the loop happens

> a 10-qubit circuit

is this a simple circuit?

> This example is illustrated in the [notebook](https://github.com/csookim/qibo_transpiler_cskim/blob/bff207ebc519313701bf0f724a757aeee243a6e6/cskim/docs/transpiler_general/21-1_qibo_sabre_looping.ipynb).

Not clear if 156 SWAPs exceeds a lot above what it should be i.e. how much of it is contributed by the loop you spotted?

Can you confirm if the loop means that Sabre shuttles back and forth?

> Discussion
 you can consider mentioning Qiskit here again just in case


### Next
- [ ] go ahead with qibo
- [ ] if no questions re my comments then please close here and merge

thanks!

**Comment by csookim** [comment]
> is this a simple circuit? 

Yes.

> Not clear if 156 SWAPs exceeds a lot above what it should be i.e. how much of it is contributed by the loop you spotted?

I revised the circuit figure after compiling with the original SABRE. The original compilation resulted in many meaningless SWAPs. The modified version shows a significant reduction, where the number of SWAPs is 17. I have added a short explanation.

> Can you confirm if the loop means that Sabre shuttles back and forth?

I revised the circuit figure after compiling with the original SABRE. The original compilation resulted in many meaningless repeated SWAPs.

**Pull request merged**
